# Generated by Django 4.2 on 2023-04-28 18:13

import acesso.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Usuário')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='E-mail')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sobrenome')),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[acesso.validators.validate_cpf], verbose_name='CPF')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone')),
                ('cep', models.CharField(max_length=15, verbose_name='CEP')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Admin')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
